### ISSUE TITLE
UInt64 type not working

### ISSUE THREAD

**Issue by jonathan-roy** [jdiaz5513/capnp-ts#119]
I have the following simple schema:

```
@0xa41619ab34c713f7;
  
struct Request {
        timestamp @0: UInt64;
}
```

Which gets compiled into the following:

```js
"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "a41619ab34c713f7";
class Request extends capnp_ts_1.Struct {
    getTimestamp() { return capnp_ts_1.Struct.getUint64(0, this); }
    setTimestamp(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "Request_" + super.toString(); }
}
Request._capnp = { displayName: "Request", id: "a62398516ab07528", size: new capnp_ts_1.ObjectSize(8, 0) };
exports.Request = Request;
```

Then, I use it like this:
```js
const capnp = require("capnp-ts");
const {Request} = require("./schemas/req.capnp.js");

const msg = new capnp.Message();
const req = msg.initRoot(Request);
req.setTimestamp(0);
```

The `req.setTimestamp(0);` call gives the following error:
```
/Users/jroy/Workspace/test/nanomsg-client/node_modules/capnp-ts/lib/serialization/segment.js:314
        this._dv.setUint8(byteOffset + 0, val.buffer[0]);
                                                    ^

TypeError: Cannot read property '0' of undefined
    at Segment.setUint64 (/Users/jroy/Workspace/test/node_modules/capnp-ts/lib/serialization/segment.js:314:53)
    at Function.setUint64 (/Users/jroy/Workspace/test/node_modules/capnp-ts/lib/serialization/pointers/struct.js:812:16)
    at Request.setTimestamp (/Users/jroy/Workspace/test/schemas/req.capnp.js:8:45)
    at Object.<anonymous> (/Users/jroy/Workspace/test/index.js:19:5)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
```

Is there something I can do to fix this?

**Comment by fasterthanlime** [comment]
> Is there something I can do to fix this?

Yes! `Uint64` is a proper class, not an alias for `number`. That's because JavaScript's number type cannot accurately represents more than 53 bits of integers (see [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)).

Internally it's represented as a Uint8Array, but it comes with handy constructor methods, so for your code, you can simply turn:

```javascript
req.setTimestamp(0);
```

into:

```javascript
req.setTimestamp(capnp.Uint64.fromNumber(0));
```

Check out the [definition of Uint64](https://github.com/jdiaz5513/capnp-ts/blob/1ace2aebdbfbedb6ef960dd07f4f3688f4e51b25/packages/capnp-ts/src/types/uint64.ts) for more helper methods.

**Comment by jonathan-roy** [comment]
Ok! Thank you for the explanation it is now working!
