### ISSUE TITLE
How to use the AnyPointer type?

### ISSUE THREAD

**Issue by jonathan-roy** [jdiaz5513/capnp-ts#120]
Hi,

I have a `Request` struct with the following schema:
```
struct Request {
	timestamp @0: UInt64;
	payload @1: AnyPointer;
}
```

The `payload` can either be a `capnp.Data` struct filled from a Node.js Buffer, or another user-defined struct (let's say a `Todo` struct for example). How am I supposed to create a message with such payload?

I tried the following:
```javascript
const msg = new capnp.Message();
const req = msg.initRoot(Request);
req.setTimestamp(capnp.Uint64.fromNumber(0));

// With a capnp.Data struct:
const payload = capnp.Struct.initStructAt(0, capnp.Data, req);
payload.copyBuffer(Buffer.from("coucou"));
req.setPayload(payload);
// or with a Todo struct:
const payload = capnp.Struct.initStrutAt(0, Todo, req);
payload.setText("Masterize capnp-ts");
payload.setDone(false);
res.setPayload(payload);
```

The payload is transmitted but the `timestamp` field seems corrupted when I set the payload. So, what is the correct way to fill this AnyPointer `payload` field?

**Comment by popham** [comment]
Your payload should probably use an [union](https://capnproto.org/language.html#unions) instead of an AnyPointer, e.g.

```
struct Request {
  timestamp @0 :UInt64;
  payload :union {
    buffer @1 :Data;
    todo @2 :Todo;
  }
}
```

**Comment by jonathan-roy** [comment]
Thank you for your answer but I can't change the schemas at the moment, is there really no way to use an `AnyPointer` field?

**Comment by popham** [comment]
Caveat: I'm not familiar enough with capnp-ts to speak authoritatively on its AnyPointer use, but I'm pretty familiar with Cap'n Proto itself.

I did notice a nasty smell coming off your use of `initStructAt` with a `capnp.Data` parameter. Data doesn't use struct encoding. It uses list encoding. And note how `initStructAt` doesn't take a length parameter to allocate the buffer's bytes. I suspect that you should use the `initData` function instead.

Your `setPayload` calls are redundant. The `initStructAt` call initializes a struct pointer within `req` and returns the object that this pointer targets. Trailing the initialization calls with set calls will clobber the pointer to target a new copy of the object within your message's arena. The old object now just sits uselessly in your message without any pointers targeting it.

Your "seems corrupted" sounds pretty weak. I checked that capnp-ts puts pointers in the message's pointers section and I'm confidant that capnp-ts doesn't put UInt64s in the pointers section. This suggests to me that the corruption is happening outside of capnp-ts. To prove corruption you can [dump](https://github.com/jdiaz5513/capnp-ts/blob/21deff545f7c744253eae6d7ded790a50eb5e3e0/packages/capnp-ts/src/serialization/message.ts#L101-L103) the message's bytes after setting the time stamp, set a pointer, then [dump](https://github.com/jdiaz5513/capnp-ts/blob/21deff545f7c744253eae6d7ded790a50eb5e3e0/packages/capnp-ts/src/serialization/message.ts#L101-L103) the message's bytes a second time. If the time stamp's bytes have been altered by setting a pointer, then you've established corruption.

**Comment by SeanTasker** [comment]
I've been doing the following:
```
const msg = new capnp.Message();
const req = msg.initRoot(Request);
req.setTimestamp(capnp.Uint64.fromNumber(0));

// With a capnp.Data struct:
let dataMsg = new capnp.Message();
let dataRoot = dataMsg.initRoot(capnp.Data);
dataRoot.copyBuffer(Buffer.from("coucou"));
req.setPayload(dataRoot);

// or with a Todo struct:
let todoMsg = new capnp.Message();
let todoRoot = dataMsg.initRoot(Todo);
todoRoot.setText("Masterize capnp-ts");
todoRoot.setDone(false);
req.setPayload(todoRoot);
```
I have not tested this but this is how I'm getting things to work.

I haven't used Data types directly with this implementation yet, but looking at the code copyBuffer looks as though it is allocating as necessary.

When you set an AnyPointer the implementation looks like it copies the data from the source. Since there are copies being made you don't need to keep the internal message references.

**Comment by jonathan-roy** [comment]
Thank you @SeanTasker, unluckily it does not seem to work with `capnp.Data` because the `Data` struct has a size of 0, thus `copyBuffer()` ignores my buffer:

From [capnp.Data.copyBuffer()](https://github.com/jdiaz5513/capnp-ts/blob/master/packages/capnp-ts/src/serialization/pointers/data.ts):
```javascript
if (dstLength < srcLength) {
    trace(
        "Truncated %d bytes from source buffer while copying to %s.",
        srcLength - dstLength,
        this
    );
}
```

**Comment by SeanTasker** [comment]
Hmm, unfortunate. Since these structures are designed to be initialised around buffers, can you create an ArrayBuffer out of your data first, initialise a message with it then `getRoot(capnp.Data)` then set that as a payload?

```
const msg = new capnp.Message();
const req = msg.initRoot(Request);
req.setTimestamp(capnp.Uint64.fromNumber(0));

// With a capnp.Data struct:
let yourReadyData = new ArrayBuffer(1234);


//Ready buffer here


let dataMsg = new capnp.Message(yourReadyData);
let dataRoot = dataMsg.getRoot(capnp.Data);
req.setPayload(dataRoot);
```

**Comment by jonathan-roy** [comment]
```js
let dataMsg = new capnp.Message(yourReadyData);
```

throws the following error:
```
Uncaught (in promise) Error: CAPNP-TS001 Attempted to parse an invalid message frame header; are you sure this is a Cap'n Proto message?
    at getFramedSegments (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/message.js:194:15)
    at initMessage (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/message.js:170:46)
    at new Message (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/message.js:51:23)
```

I also tried to pass an empty `ArrayBuffer` then fill it with the real buffer:
```javascript
const msg = new capnp.Message(new ArrayBuffer(yourReadyData.length));
const payloadStruct = msg.getRoot(capnp.Data);
```

But then I have the following error:
```
Uncaught (in promise) RangeError: Offset is outside the bounds of the DataView
    at DataView.getFloat64 (<anonymous>)
    at Segment.isWordZero (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/segment.js:199:25)
    at isNull (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/pointers/pointer.js:571:22)
    at Object.validate (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/pointers/pointer.js:683:9)
    at getRoot (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/message.js:274:15)
    at Message.getRoot (/Users/jroy/Workspace/test/test/node_modules/capnp-ts/lib/serialization/message.js:78:16)
```

**Comment by SeanTasker** [comment]
Damn. But that does make sense since it is looking for a correctly formatted buffer.

Lack of build examples is actually my main issue with this implementation, capno too for more unusual use cases - of building structures.

I just opened an issue about creating structures and the problem I'm having along my no-guide path.

Reading is arguably very trivial, but there aren't many examples of creating structures beyond the address book one, which is very direct and single use case.

@jdiaz5513 are you able to enlighten us?

**Comment by jonathan-roy** [comment]
I finally found a **very hacky** way to fill the `capnp.Data` struct. First, I created a `DataBox` struct with the following schema:

```
@0x915f3367709de788;
  
struct DataBox {
        value @0 :Data;
}
```

Then I use it like this:
```javascript
const msg = new capnp.Message();
const dataBox = msg.initRoot(DataBox);
dataBox.initValue(yourReadyData.length);
const payload = dataBox.getValue();
payload.copyBuffer(yourReadyData);
req.setPayload(payload);
```

It is obviously not ideal so I won't close this issue, but it seems to work.

**Comment by ndisidore** [comment]
Sorry for the necro thread, but this still seems to be an issue: this could definitely be user error, but as far as I can tell a few data types (Data & AnyPointer are the ones tested) are near impossible to use because `copyBuffer` has some fundamental issues in that it assumes your destination buffer is (at least) the right size.

In my setup, I'm working with a protobuf struct like
```
struct MyStruct {
  value @0 :Data;
}
```
Accompanying JS code looks like
```js
const prepopulatedBuffer = new TextEncoder().encode('test')

const msg = new capnp.Message()
const myStruct = msg.initRoot(MyStruct)
const data = new capnp.Message().initRoot(capnp.Data)
...
```
I'd like to copy an externally populated Uint8Array `prepopulatedBuffer` to `data`. However, passing both the raw Uint8Array and the Uint8Array as an ArrayBuffer (via `prepopulatedBuffer.buffer`) don't accomplish this because copyBuffer truncates based on the destination size (which I haven't found a way to not be 0 yet) and results in the same behavior @jonathan-roy was seeing.

**Comment by jdiaz5513** [comment]
@ndisidore Sorry for the necro response. ;)

The core issue happens here:

```typescript
const data = new capnp.Message().initRoot(capnp.Data)
```

`initRoot` is only intended to be used with `Struct`s. `Data` is technically a `List` pointer and capnp messages -- as per the spec -- must always begin with a `Struct`. The `initRoot` call ends up yielding a zero-length blob so you end up with nothing to copy into, as you have observed.

It is an issue that `.initRoot` allows this at all.

Admittedly the API for doing this correctly was not documented well enough. In v0.9.0 this got much easier with property accessors. This is perhaps what you were looking for:

```typescript
const prepopulatedBuffer = new TextEncoder().encode('test');
const msg = new capnp.Message();
const myStruct = msg.initRoot(MyStruct);

/* this is how it was done before v0.9.0, and still works this way under the hood today: */
myStruct.initValue(prepopulatedBuffer.byteLength).copyBuffer(prepopulatedBuffer);
/* now direct property assignment is possible: */
myStruct.value = prepopulatedBuffer;
/* or using the new `set` function, which is just like calling Object.assign: */
myStruct.set({ value: prepopulatedBuffer });

/* also new in v0.9.0: */
console.log(myStruct.toJSON());  // { value: "dGVzdA==" }
```

`.value` and `.set()` also now accept a base64-encoded string (and base64 is how `.toJSON()` is implemented for `Data`).

Please comment if any of the above doesn't work, otherwise open a new issue if there's any problems with upgrading to v0.9.0.
