### ISSUE TITLE
Requiring capnp files not working.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [jdiaz5513/capnp-ts#122]
Wanting to make a custom compiler plugin for capnp with node v12.2.0 running on Windows 10.

Looks like the loader for require capnp files is not working, any thoughts did I set something up wrong?

Used example from readme.

```js
const capnp = require('capnp-ts');
const schema = require("./capnp/schema.capnp").CodeGeneratorRequest;
```

```
# Copyright (c) 2013-2014 Sandstorm Development Group, Inc. and contributors
^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\Source\OperationSpatial\capnp-to-jsbuffer\index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:756:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```

Looking at the address book example in packages dir it requires a .js file which must first be generated.

Needed to use this command as capnpc was not found.
```
capnp compile -o js addressbook.capnp
```

**Comment by LiamKarlMitchell** [comment]
Possibly the readme is not quite right for the compile command.

**Comment by jdiaz5513** [comment]
Please open a new issue if this is still an issue as of v0.9.0. The README and compiler have both been significantly upgraded since this posting.
