### ISSUE TITLE
Addressbook js example has errors.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [jdiaz5513/capnp-ts#123]
Node.js v12.2.0

node addressbook write | node addressbook read
```
(node:51772) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: CAPNP-TS023 Cannot convert Pointer_0@0x00000028,[21 00 00 00 3f 00 00 00],limit:0x7ffffffc to a BYTE list.
    at Object.validate (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\pointer.js:695:19)
    at Function.Text.fromPointer (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\text.js:21:19)
    at Function.getText (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\struct.js:478:25)
    at Person.getEmail (D:\Source\capnp-ts-master\packages\js-examples\addressbook.capnp.js:70:43)
    at D:\Source\capnp-ts-master\packages\js-examples\addressbook.js:94:52
    at class_1.List.forEach (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\list.js:121:13)
    at D:\Source\capnp-ts-master\packages\js-examples\addressbook.js:93:29
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by LiamKarlMitchell** [comment]
Even using Buffer.from still get an error when reading.
```
Error: CAPNP-TS023 Cannot convert Pointer_0@0x00000028,[21 00 00 00 3f 00 00 00],limit:0x7ffffffc to a BYTE list.
    at Object.validate (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\pointer.js:695:19)
    at Function.Text.fromPointer (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\text.js:21:19)
    at Function.getText (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\struct.js:478:25)
    at Person.getEmail (D:\Source\capnp-ts-master\packages\js-examples\addressbook.capnp.js:70:43)
    at D:\Source\capnp-ts-master\packages\js-examples\addressbook.js:94:52
    at class_1.List.forEach (D:\Source\capnp-ts-master\packages\js-examples\node_modules\capnp-ts\lib\serialization\pointers\list.js:121:13)
    at D:\Source\capnp-ts-master\packages\js-examples\addressbook.js:93:29
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by ptrjeffrey** [comment]
I got the same issue with fs stream.
But when I use socket.io the issue disappeared.
The demo works under socket.io env

**Comment by jdiaz5513** [comment]
The js examples are working in the current version; closing.
