### ISSUE TITLE
Cannot create property 'pos' when used with Capnproto 1.0 compiler

### ISSUE THREAD

**Issue by dattanchu** [jdiaz5513/capnp-ts#178]
When I run capnp compiler of Capnproto 1.0 version, I am getting 

```
TypeError: Cannot create property 'pos' on string 'AppContext_DeviceOrientation'
    at setTextRangePos (/private/var/tmp/.../node_modules/typescript/lib/typescript.js:21342:19)
    at Object.setTextRangePosEnd (/private/var/tmp/.../node_modules/typescript/lib/typescript.js:21360:32)
    at createNodeArray (/private/var/tmp/.../node_modules/typescript/lib/typescript.js:22985:16)
    at Object.createEnumDeclaration (/private/var/tmp/.../node_modules/typescript/lib/typescript.js:25548:28)
    at Object.createEnumDeclaration (/private/var/tmp/.../node_modules/typescript/lib/typescript.js:3138:29)
    at generateEnumNode (/private/var/tmp/.../node_modules/capnpc-ts/src/generators.js:117:36)
    at generateNode (/private/var/tmp/.../node_modules/capnpc-ts/src/generators.js:159:13)
    at /private/var/tmp/.../node_modules/capnpc-ts/src/generators.js:148:32
    at Array.forEach (<anonymous>)
    at Object.generateNode (/private/var/tmp/.../node_modules/capnpc-ts/src/generators.js:148:17)
```

This happens for all .capnp files. The command that I use to run is

```
bin/external/capnproto/capnp compile --verbose --no-standard-import -o./node_modules/capnpc-js/bin/capnpc-js.js:bazel-out/darwin_arm64-fastbuild/bin -Iexternal/capnproto/c++/src -Ithird_party/capnpcs/compiler -Iexternal/capnproto_java/compiler/src/main/schema .../app.capnp
```

Any tips on how I can help debug this issue? Has anyone tried the latest capnproto version with capnp-ts? I tried running my C++ only executables and they run ok.

**Comment by Doris0812** [comment]
Have you solved it now?

**Comment by dattanchu** [comment]
I have not solved the issue. I believe the error is a red herring. Something has changed in capnpc 1.0 and this breaks capnp-ts.

**Comment by bartoszflis-silvair** [comment]
I've fixed a `Cannot create property 'pos' on string` error by using the following config in `package.json`. Used capnpc 0.7.0 though, so YMMV.
```
  "engines": {
    "node": "<=23",
    "npm": ">8.4"
  },
  "dependencies": {
    "@types/debug": "^4.1.12",
    "capnpc-js": "0.5.1",
    "capnpc-ts": "0.7.0",
    "ts-node": "~7.0.0",
    "typescript": "<4"
  },
  "overrides": {
    "typescript": "$typescript"
  }
```

**Comment by shestakov-bc** [comment]
In my case it worked with `capnpc 0.8.0` which is bundled by default with Ubuntu 22.04. I did also tried manually built `0.7.0`, and got same results. It only worked with package `"capnpc-ts": "0.4.0"`.  Even `0.5.0` would throw same error. Trying different version of typescript or ts-node wouldn't change a thing for me. I hope it will unlock someone sooner, I lost half a day with this.

**Comment by emdgit** [comment]
@shestakov-bc Still helps. Thanks!

**Comment by jdiaz5513** [comment]
Should be fixed as of the codegen rewrite in #186. Please comment if it still occurs after updating to 0.9.0.
