### ISSUE TITLE
linux capnpc -o js xxx.capnp  Cannot create property 'pos' on string 'TestView'

### ISSUE THREAD

**Issue by Doris0812** [jdiaz5513/capnp-ts#179]
capnpc -o js test.capnp
DeprecationWarning: 'createTypeReferenceNode' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createToken' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createThis' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createNamespaceImport' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createExpressionStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createVariableDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createVariableDeclarationList' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createVariableStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createPropertyAssignment' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createNumericLiteral' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createNewExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createObjectLiteralExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createPropertyDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: '' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createCallExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createReturnStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createBlock' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createMethodDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createLogicalNot' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createBinaryExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createExpressionWithTypeArguments' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createHeritageClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createClassDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
TypeError: Cannot create property 'pos' on string 'TestView'
    at setTextRangePos (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:21342:19)
    at Object.setTextRangePosEnd (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:21360:32)
    at createNodeArray (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:22985:16)
    at asNodeArray (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:27581:28)
    at createBaseGenericNamedDeclaration (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:23037:35)
    at createBaseInterfaceOrClassLikeDeclaration (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:23072:24)
    at createBaseClassLikeDeclaration (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:23078:24)
    at Object.createClassDeclaration (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:25474:24)
    at Object.createClassDeclaration (/usr/local/lib/node_modules/capnpc-js/node_modules/typescript/lib/typescript.js:3138:29)
    at generateStructNode (/usr/local/lib/node_modules/capnpc-js/node_modules/capnpc-ts/src/generators.js:494:36)
js: plugin failed: exit code 1

**Comment by bartoszflis-silvair** [comment]
See my comment here, might help: https://github.com/jdiaz5513/capnp-ts/issues/178#issuecomment-2431579443

**Comment by jdiaz5513** [comment]
Should be fixed as of the codegen rewrite in #186. Please reopen if it still occurs after updating to 0.9.0.
