### ISSUE TITLE
Failure to compile schema for address.capnp

### ISSUE THREAD

**Issue by Pooja71** [jdiaz5513/capnp-ts#65]
capnpc -onode_modules/capnpc-js/bin/capnpc-js.js addressbook.capnp

RangeError: Offset is outside the bounds of the DataView
    at DataView.getInt32 (native)
    at Segment.getInt32 (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnp-ts/lib/serialization/segment.js:132:29)
    at Pointer._getOffsetWords (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnp-ts/lib/serialization/pointers/pointer.js:326:33)
    at class_1.Pointer._getTargetListLength (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnp-ts/lib/serialization/pointers/pointer.js:405:58)
    at class_1.List.getLength (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnp-ts/lib/serialization/pointers/list.js:69:25)
    at class_1.List.map (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnp-ts/lib/serialization/pointers/list.js:72:31)
    at generateStructNode (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/generators.js:323:49)
    at generateNode (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/generators.js:105:17)
    at /Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/generators.js:101:50
    at Array.forEach (native)
    at Object.generateNode (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/generators.js:101:20)
    at /Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/compiler.js:24:158
    at Array.forEach (native)
    at compile (/Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/compiler.js:24:115)
    at /Users/pooja/Desktop/ulema_backup/capnp-ts_implementation/node_modules/capnpc-ts/lib/compiler.js:48:40
    at Array.forEach (native)
node_modules/capnpc-js/bin/capnpc-js.js: plugin failed: exit code 1

**Comment by jdiaz5513** [comment]
Eep. You might have to wait for my fixes to the serialization code (this also should have been caught by an automated test 😞 ). I'm working on it today, will update here when it's working.

**Comment by Pooja71** [comment]
Sure! Thanks a lot. Will wait for the update :)

**Comment by jdiaz5513** [comment]
@Pooja71 after looking at this a bit more I'm realizing you probably ran into #46. I've patched this in master and will publish that soon. This will happen if you attempt to pass a CodeGeneratorRequest from capnp 0.6.0.

My suspicion is that the version of capnpc that you're using is out of date; you need to upgrade to 0.6.1. I'll start logging a warning when this isn't the case.
